# Generated by Django 3.1.7 on 2021-03-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210323_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='username',
        ),
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
